# Generated by Django 5.1.7 on 2025-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_cars_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_details',
            name='car_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
