# Generated by Django 5.1.7 on 2025-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_cars_details_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_details',
            name='car_image',
            field=models.ImageField(default=1, upload_to='car_photos'),
            preserve_default=False,
        ),
    ]
