# Generated by Django 5.1.7 on 2025-03-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_cars_details_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars_details',
            name='car_booking',
        ),
        migrations.RemoveField(
            model_name='cars_details',
            name='car_details',
        ),
    ]
