# Generated by Django 5.1.7 on 2025-03-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
